version: '3'
services:
  postgresql:
    image: postgres:13
    volumes:
      - hw_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hw_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432

volumes:
  hw_data:
