version: '3'
services:
  keycloak-postgresql:
    image: postgres:13
    volumes:
      - keycloak_postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
