server:
  port: 8081

spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: auth-service
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8093/auth/realms/dh
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8094/auth/realms/dh
