server:
  port: 8081

spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${keycloak.clientId}
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${keycloak.authServerUrl}/realms/${keycloak.realm}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.authServerUrl}/realms/${keycloak.realm}

keycloak:
  authServerUrl: http://localhost:8093/auth
  realm: dh
  clientId: auth-service
  credentials:
    secret: 37qajpFSzTw02Ao1r6Baa1qASqwY8STU
